# Generated by Django 2.1.5 on 2019-01-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shout_name', models.CharField(max_length=200)),
                ('shout_text', models.CharField(max_length=200)),
                ('shout_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
